@base_url = http://localhost:9100
@client_id = client
@client_secret = secret
@username = admin
@password = admin
@access_token = bfa29bd9-860c-42b2-b8f8-480ff4ace17f
@refresh_token = 09a9f88b-e215-4abc-8ca3-4c6f11a7688d

### /oauth/token

POST {{base_url}}/oauth/token?client_id={{client_id}}&client_secret={{client_secret}}&grant_type=password&username={{username}}&password={{password}}
Content-Type: application/json

### /oauth/check_token

POST {{base_url}}/oauth/check_token?token={{access_token}}
Content-Type: application/json

### /oauth/check_token

POST {{base_url}}/oauth/token?client_id={{client_id}}&client_secret={{client_secret}}&grant_type=refresh_token&refresh_token={{refresh_token}}
Content-Type: application/json
