@base_url = http://localhost:9100
@client_id = client
@client_secret = secret
@username = admin
@password = admin
@access_token = 22bf1fba-19f7-4ac7-9229-e19b0b9e4053

### /oauth/token

POST {{base_url}}/oauth/token?client_id={{client_id}}&client_secret={{client_secret}}&grant_type=password&username={{username}}&password={{password}}
Content-Type: application/json

### /oauth/check_token

POST {{base_url}}/oauth/check_token?token={{access_token}}
Content-Type: application/json
