@base_url = http://localhost:9100
@client_id = client
@client_secret = secret
@redirect_uri = http://example.com
@code = 2iU9qX

### /oauth/authorize

GET {{base_url}}/oauth/authorize?response_type=code&client_id=client&scop=all&redirect_uri=http://example.com

### /oauth/token

POST {{base_url}}/oauth/token?client_id={{client_id}}&client_secret={{client_secret}}&grant_type=authorization_code&code={{code}}&redirect_uri={{redirect_uri}}
Content-Type: application/json

### /oauth/check_token

curl -i -X POST  -u 'demoApp:demoAppSecret' -d 'grant_type=refresh_token&refresh_token=95844d87-f06e-4a4e-b76c-f16c5329e287' http://localhost:8080/oauth/token
