@base_url = http://localhost:9100
@client_id = client
@client_secret = secret
@username = admin
@password = admin

### /oauth/token

POST {{base_url}}/oauth/token?client_id={{client_id}}&client_secret={{client_secret}}&grant_type=password&username={{username}}&password={{password}}
Content-Type: application/json
