# Undertow settings
server:
  port: ${SERVER_PORT:8080}
  undertow:
    threads:
      io: ${UNDERTOW_IO_THREADS:1}
      worker: ${UNDERTOW_WORKER_THREADS:8}
    buffer-size: ${UNDERTOW_BUFFER_SIZE:1024}

# Management settings
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    elasticsearch:
      enabled: false

# Logging settings
logging:
  level:
    root: ERROR
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      example: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:100MB}
    max-history: ${LOGGING_FILE_MAX_HISTORY:50}

# Knife4j settings
knife4j:
  enable: true
  setting:
    enableGroup: false
    enableOpenApi: false
    enableFooterCustom: true
    footerCustomContent: 版权所有 | Copyright 2021

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: ss-single-backend
